def eve_mad_lib():
    print("Welcome!")
    adj1 = input("Enter a adjective: ")
    adj2 = input("Enter another adjective: ")
    noun1 = input("Enter a noun: ")
    noun2 = input("Enter another noun: ")
    pluralNoun1 = input("Enter a plural noun: ")
    game = input("Enter the name of a game: ")
    pluralNoun2 = input("Enter another plural noun: ")
    ingVerb1 = input("Enter a verb ending in 'ing': ")
    ingVerb2 = input("Enter another verb ending in 'ing': ")
    pluralNoun3 = input("Enter another plural noun: ")
    ingVerb3 = input("Enter another verb ending in 'ing': ")
    noun3 = input("Enter another noun: ")
    plant = input("Enter the name of a plant: ")
    body = input("Enter a body part: ")
    place = input("Enter a place: ")
    ingVerb4 = input("Enter another verb ending in 'ing': ")
    adj3 = input("Enter another adjective: ")
    num = int(input("Enter a number: "))
    pluralNoun4 = input("Enter another plural noun: ")

    print("A vacation is when you take a trip to some", adj1, "place with your", adj2, "family. Usually you go to some place that is near a/an", noun1, "or up on a/an", noun2, ". A good vacation place is one where you can ride", pluralNoun1, "or play", game, "or go hunting for", pluralNoun2, ". I like to spend my time", ingVerb1, "or", ingVerb2, ". When parents go on a vacation, they spend their time eating three", pluralNoun3, "a day, and fathers play golf, and mothers sit around", ingVerb3, ".")

if __name__ == "__main__":
    eve_mad_lib()
